version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app-frontend"
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "elm"
    directory: "/app-frontend"
    schedule:
      interval: "daily"
    labels:
      - "elm"
      - "dependencies"
